/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogra2;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.WindowConstants;

/**
 *
 * @author hapav
 */
public class Main extends javax.swing.JFrame {

    private int night = 0;
    private SwingWorker<Void, String> clockWorker;

    private boolean RightdoorClosed = false;
    private boolean LeftdoorClosed = false;
    private boolean RightLighton = false;
    private boolean LeftLighton = false;

    public Main() {
        initComponents();

        Ds_Extra.show(false);
        Ds_Extra2.show(false);
        Ds_Extra3.show(false);
        jLabel2.show(false);
        jLabel6.show(false);
        jLabel11.setVisible(false);
        jLabel13.setVisible(false);
        jLabel12.setVisible(false);
        jLabel15.show(false);
        jLabel17.setVisible(false);
        jLabel21.show(false);
        jLabel24.show(false);
        jLabel25.show(false);
        jLabel26.show(false);
        jLabel27.show(false);
//        jTextField11.setBackground(new java.awt.Color(0, 0, 0, 1));
//
//        jTextField12.setBackground(new java.awt.Color(0, 0, 0, 1));
//
//        jTextField13.setBackground(new java.awt.Color(0, 0, 0, 1));
//
//        jTextField10.setBackground(new java.awt.Color(0, 0, 0, 1));
        jTextField2.setBackground(new java.awt.Color(0, 0, 0, 1));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0, 1));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0, 1));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0, 1));

        jTextField9.setBackground(new java.awt.Color(0, 0, 0, 1));

        jTextField5.setBackground(new java.awt.Color(0, 0, 0, 1));

        jTextField7.setBackground(new java.awt.Color(0, 0, 0, 1));

//        jDialog1.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
//        jDialog1.addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosing(WindowEvent e) {
//
//                System.exit(0);
//            }
//        });
//
//        jDialog1.pack();
//        jDialog1.setModal(true);
//        jDialog1.setLocationRelativeTo(this);
//        jDialog1.setVisible(true);
//
//        Admin ap
//                = new Admin("./blady.txt");
//        ap.cargarArchivo();
//
//        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jComboBox1.getModel();
//
//        for (Usuario t : ap.getListaPersonas()) {
//            modelo.addElement(t.toString());
//        }
//        jComboBox1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewGame = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        Cam1A = new javax.swing.JButton();
        Cam2 = new javax.swing.JButton();
        Cam6 = new javax.swing.JButton();
        Cam4A = new javax.swing.JButton();
        Cam4B = new javax.swing.JButton();
        Cam2A = new javax.swing.JButton();
        Cam2B = new javax.swing.JButton();
        Cam3 = new javax.swing.JButton();
        Cam1C = new javax.swing.JButton();
        Cam1B = new javax.swing.JButton();
        Cam5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        Ds_Extra2 = new javax.swing.JTextField();
        Ds_Extra3 = new javax.swing.JTextField();
        Ds_Extra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        NewGame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmbosprendidosIzq.png"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 90, 240));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Camaras.jpg"))); // NOI18N
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 720, 500));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ABRIIRRR.gif"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 720, 500));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmboPrendidoder.png"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 280, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC Computer - Five Nights at Freddys - Buttons.png"))); // NOI18N
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 290, 100, 180));

        jLabel18.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 110, 120, 40));

        jLabel19.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 70, 120, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuertaIzquierdaBotonApagado.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 300, 100, 160));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuertaDerechaPuertaEncendida.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 270, 100, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif-4-807c3586c6.gif"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 220, 550));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puertacerrder (1).gif"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, 200, 560));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kitchen.jpg"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 440, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif-4-6ac0f3ab68.gif"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 190, 510));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BottonDerechoApagado.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 90, 210));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotoderechoEncendidoLapuerta.png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 100, 280));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuzEncendidabIzqu.png"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 90, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wqtbx5bl97311_2.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 650));

        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 310, 40, 50));

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 80));

        jButton3.setText("jButton3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 50, 80));

        jButton4.setText("jButton4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 390, 60, 80));

        jLabel23.setText("jLabel23");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 300, -1, 180));

        Cam1A.setText("jButton5");
        Cam1A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cam1AMouseClicked(evt);
            }
        });
        jPanel3.add(Cam1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 40, -1));

        Cam2.setText("jButton5");
        jPanel3.add(Cam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 425, 40, 20));

        Cam6.setText("jButton5");
        jPanel3.add(Cam6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 505, 40, 30));

        Cam4A.setText("jButton5");
        jPanel3.add(Cam4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 40, -1));

        Cam4B.setText("jButton5");
        jPanel3.add(Cam4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 555, 40, 30));

        Cam2A.setText("jButton5");
        jPanel3.add(Cam2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 40, -1));

        Cam2B.setText("jButton5");
        jPanel3.add(Cam2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 40, -1));

        Cam3.setText("jButton5");
        jPanel3.add(Cam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 40, -1));

        Cam1C.setText("jButton5");
        jPanel3.add(Cam1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 455, 30, 20));

        Cam1B.setText("jButton6");
        jPanel3.add(Cam1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 40, -1));

        Cam5.setText("jButton5");
        jPanel3.add(Cam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 40, -1));

        NewGame.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 690));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puertaizcerrada.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        NewGame.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puertaizqrabrir.gif"))); // NOI18N
        jLabel5.setText("jLabel5");
        NewGame.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puertadercerrada.gif"))); // NOI18N
        jLabel7.setText("jLabel7");
        NewGame.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puertaderabrir.gif"))); // NOI18N
        jLabel8.setText("jLabel8");
        NewGame.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenDelMonitor.gif"))); // NOI18N
        jLabel12.setText("jLabel12");
        NewGame.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Monicerrar.gif"))); // NOI18N
        jLabel13.setText("jLabel13");
        NewGame.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuzEncendidaC.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        NewGame.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuzEncendidaIzq.jpg"))); // NOI18N
        jLabel22.setText("jLabel22");
        NewGame.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("At");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 146, 50));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Five ");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 146, 44));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Nights");
        jTextField3.setBorder(null);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 146, 44));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("Freddy's");
        jTextField4.setBorder(null);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 146, 44));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("Continue");
        jTextField5.setBorder(null);
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField5MouseExited(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, 44));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("New Game");
        jTextField9.setBorder(null);
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField9MouseExited(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 44));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("Costume Night");
        jTextField7.setBorder(null);
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField7MouseExited(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 260, 44));

        Ds_Extra2.setEditable(false);
        Ds_Extra2.setBackground(new java.awt.Color(0, 0, 0));
        Ds_Extra2.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        Ds_Extra2.setForeground(new java.awt.Color(255, 255, 255));
        Ds_Extra2.setText("       <<");
        Ds_Extra2.setBorder(null);
        jPanel1.add(Ds_Extra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 150, 44));

        Ds_Extra3.setEditable(false);
        Ds_Extra3.setBackground(new java.awt.Color(0, 0, 0));
        Ds_Extra3.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        Ds_Extra3.setForeground(new java.awt.Color(255, 255, 255));
        Ds_Extra3.setText(" <<");
        Ds_Extra3.setBorder(null);
        jPanel1.add(Ds_Extra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 146, 44));

        Ds_Extra.setEditable(false);
        Ds_Extra.setBackground(new java.awt.Color(0, 0, 0));
        Ds_Extra.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        Ds_Extra.setForeground(new java.awt.Color(255, 255, 255));
        Ds_Extra.setText("       <<");
        Ds_Extra.setBorder(null);
        Ds_Extra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ds_ExtraMouseEntered(evt);
            }
        });
        jPanel1.add(Ds_Extra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 150, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ezgif-3-5dfb267f23.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1130, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 989, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ds_ExtraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ds_ExtraMouseEntered


    }//GEN-LAST:event_Ds_ExtraMouseEntered

    private void jTextField9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseEntered

        Ds_Extra.setVisible(true);
        Ds_Extra.setBackground(new java.awt.Color(0, 0, 0, 1));

    }//GEN-LAST:event_jTextField9MouseEntered

    private void jTextField9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseExited
        Ds_Extra.setVisible(false);
    }//GEN-LAST:event_jTextField9MouseExited

    private void jTextField5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseEntered
        Ds_Extra2.setVisible(true);
        Ds_Extra2.setBackground(new java.awt.Color(0, 0, 0, 1));
    }//GEN-LAST:event_jTextField5MouseEntered

    private void jTextField5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseExited
        Ds_Extra2.setVisible(false);
    }//GEN-LAST:event_jTextField5MouseExited

    private void jTextField7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseEntered
        Ds_Extra3.setVisible(true);
        Ds_Extra3.setBackground(new java.awt.Color(0, 0, 0, 1));
    }//GEN-LAST:event_jTextField7MouseEntered

    private void jTextField7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseExited
        Ds_Extra3.setVisible(false);
    }//GEN-LAST:event_jTextField7MouseExited

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked

        if (night != 4) {
            startClockSimulation();
        } else {
            startClockSimulation();
            night = 0;
        }

        night++;
        jLabel19.setForeground(Color.WHITE);
        jLabel19.setFont(jTextField2.getFont());
        jLabel19.setText("Night: " + Integer.toString(night));

        NewGame.pack();
        NewGame.setModal(true);
        NewGame.setLocationRelativeTo(this);
        NewGame.setVisible(true);


    }//GEN-LAST:event_jTextField9MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        Timer timer = null;

        if (cont % 2 != 0) {
            RightdoorClosed = true;

            if (LeftLighton) {
                jLabel14.setVisible(false);
                jLabel15.setVisible(false);
                jLabel25.setVisible(true);

            } else {
                jLabel14.setVisible(false);
                jLabel15.setVisible(true);
                jLabel25.setVisible(false);
            }

            ImageIcon originalIcon = (ImageIcon) jLabel2.getIcon();
            Image originalImage = originalIcon.getImage();
            ImageIcon newIcon = new ImageIcon(originalImage);

            jLabel2.setIcon(newIcon);

            int duration = 650;
            int lastFrameIndex = originalIcon.getIconHeight();

            if (timer != null && timer.isRunning()) {
                timer.stop();
            }

            timer = new Timer(duration, new ActionListener() {
                private boolean animationStarted = false;
                private boolean isClosed = false;

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!animationStarted) {
                        animationStarted = true;

                        BufferedImage bufferedImage = new BufferedImage(newIcon.getIconWidth(), lastFrameIndex + 1, BufferedImage.TYPE_INT_ARGB);
                        Graphics2D g2d = bufferedImage.createGraphics();
                        g2d.drawImage(newIcon.getImage(), 0, 0, null);
                        g2d.dispose();

                        ImageIcon lastFrameIcon = new ImageIcon(bufferedImage);

                        jLabel2.setIcon(lastFrameIcon);

                        if (isClosed) {
                            jLabel2.setVisible(false);
                            ((Timer) e.getSource()).stop();
                        } else {
                            jLabel2.setIcon(jLabel3.getIcon());
                        }
                    }
                }
            });

            jLabel2.setVisible(true);
            timer.start();
            cont++;
        } else if (cont % 2 == 0 && RightdoorClosed) {
            // Caso 3: Puerta derecha abierta y previamente cerrada con la luz encendida
            jLabel14.setVisible(true);
            jLabel15.setVisible(false);
            jLabel25.setVisible(false);
            RightdoorClosed = false;
            ImageIcon originalIcon = (ImageIcon) jLabel5.getIcon();
            Image originalImage = originalIcon.getImage();
            ImageIcon newIcon = new ImageIcon(originalImage);
            jLabel2.setIcon(newIcon);

            int duration = 650;
            int lastFrameIndex = originalIcon.getIconHeight();

            if (timer != null && timer.isRunning()) {
                timer.stop();
            }

            timer = new Timer(duration, new ActionListener() {
                private boolean animationStarted = false;

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!animationStarted) {
                        animationStarted = true;

                        BufferedImage bufferedImage = new BufferedImage(newIcon.getIconWidth(), lastFrameIndex + 1, BufferedImage.TYPE_INT_ARGB);
                        Graphics2D g2d = bufferedImage.createGraphics();
                        g2d.drawImage(newIcon.getImage(), 0, 0, null);
                        g2d.dispose();

                        ImageIcon lastFrameIcon = new ImageIcon(bufferedImage);

                        jLabel2.setIcon(lastFrameIcon);
                        jLabel2.setVisible(false);
                    }
                }
            });

            jLabel2.setVisible(true);
            timer.start();
            cont++;
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        Timer timer = null;

        if (cont2 % 2 != 0) {
            LeftdoorClosed = true;

            if (RightLighton) {
                jLabel16.setVisible(false);
                jLabel17.setVisible(false);
                jLabel26.setVisible(true);
            } else {
                jLabel16.setVisible(false);
                jLabel17.setVisible(true);
                jLabel26.setVisible(false);
            }

            ImageIcon originalIcon = (ImageIcon) jLabel6.getIcon();
            Image originalImage = originalIcon.getImage();
            ImageIcon newIcon = new ImageIcon(originalImage);

            jLabel6.setIcon(newIcon);

            int duration = 650;
            int lastFrameIndex = originalIcon.getIconHeight();

            if (timer != null && timer.isRunning()) {
                timer.stop();
            }

            timer = new Timer(duration, new ActionListener() {
                private boolean animationStarted = false;
                private boolean isClosed = false;

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!animationStarted) {
                        animationStarted = true;

                        BufferedImage bufferedImage = new BufferedImage(newIcon.getIconWidth(), lastFrameIndex + 1, BufferedImage.TYPE_INT_ARGB);
                        Graphics2D g2d = bufferedImage.createGraphics();
                        g2d.drawImage(newIcon.getImage(), 0, 0, null);
                        g2d.dispose();

                        ImageIcon lastFrameIcon = new ImageIcon(bufferedImage);

                        jLabel6.setIcon(lastFrameIcon);

                        if (isClosed) {
                            jLabel6.setVisible(false);
                            ((Timer) e.getSource()).stop();
                        } else {
                            jLabel6.setIcon(jLabel7.getIcon());
                        }
                    }
                }
            });

            jLabel6.setVisible(true);
            timer.start();
            cont2++;
        } else if (cont2 % 2 == 0 && LeftdoorClosed) {
            // Caso 3: Puerta izquierda abierta y previamente cerrada con la luz encendida
            jLabel16.setVisible(true);
            jLabel17.setVisible(false);
            jLabel26.setVisible(false);
            jLabel24.show(false);
            LeftdoorClosed = false;

            ImageIcon originalIcon = (ImageIcon) jLabel8.getIcon();
            Image originalImage = originalIcon.getImage();
            ImageIcon newIcon = new ImageIcon(originalImage);
            jLabel6.setIcon(newIcon);

            int duration = 650;
            int lastFrameIndex = originalIcon.getIconHeight();

            if (timer != null && timer.isRunning()) {
                timer.stop();
            }

            timer = new Timer(duration, new ActionListener() {
                private boolean animationStarted = false;

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!animationStarted) {
                        animationStarted = true;

                        BufferedImage bufferedImage = new BufferedImage(newIcon.getIconWidth(), lastFrameIndex + 1, BufferedImage.TYPE_INT_ARGB);
                        Graphics2D g2d = bufferedImage.createGraphics();
                        g2d.drawImage(newIcon.getImage(), 0, 0, null);
                        g2d.dispose();

                        ImageIcon lastFrameIcon = new ImageIcon(bufferedImage);

                        jLabel6.setIcon(lastFrameIcon);
                        jLabel6.setVisible(false);
                    }
                }
            });

            jLabel6.setVisible(true);
            timer.start();

            cont2++;
        }


    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        Timer timer;

        if (cont3 % 2 != 0) {
            ImageIcon originalIcon = (ImageIcon) jLabel11.getIcon();
            Image originalImage = originalIcon.getImage();
            ImageIcon newIcon = new ImageIcon(originalImage);
            jLabel11.setIcon(newIcon);

            int duration = 650;
            int lastFrameIndex = originalIcon.getIconHeight();

            timer = new Timer(duration, new ActionListener() {
                private boolean animationStarted = false;
                private boolean isClosed = false;

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!animationStarted) {
                        animationStarted = true;

                        BufferedImage bufferedImage = new BufferedImage(newIcon.getIconWidth(), lastFrameIndex + 1, BufferedImage.TYPE_INT_ARGB);
                        Graphics2D g2d = bufferedImage.createGraphics();
                        g2d.drawImage(newIcon.getImage(), 0, 0, null);
                        g2d.dispose();

                        ImageIcon lastFrameIcon = new ImageIcon(bufferedImage);

                        jLabel11.setIcon(lastFrameIcon);

                        if (isClosed) {
                            jLabel11.setVisible(false);
                            ((Timer) e.getSource()).stop();
                        } else {
                            jLabel11.setIcon(jLabel12.getIcon());
                        }
                    }
                }
            });

            jLabel11.setVisible(true);
            timer.start();
            
            cont3++;
            jLabel27.show(true);
        } else if (cont3 % 2 == 0) {
            ImageIcon originalIcon = (ImageIcon) jLabel13.getIcon();
            Image originalImage = originalIcon.getImage();
            ImageIcon newIcon = new ImageIcon(originalImage);
            jLabel11.setIcon(newIcon);

            int duration = 650;
            int lastFrameIndex = originalIcon.getIconHeight();

            timer = new Timer(duration, new ActionListener() {
                private boolean animationStarted = false;

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!animationStarted) {
                        animationStarted = true;

                        BufferedImage bufferedImage = new BufferedImage(newIcon.getIconWidth(), lastFrameIndex + 1, BufferedImage.TYPE_INT_ARGB);
                        Graphics2D g2d = bufferedImage.createGraphics();
                        g2d.drawImage(newIcon.getImage(), 0, 0, null);
                        g2d.dispose();

                        ImageIcon lastFrameIcon = new ImageIcon(bufferedImage);

                        jLabel11.setIcon(lastFrameIcon);
                        jLabel11.setVisible(false);
                    }
                }
            });

            jLabel11.setVisible(true);
            jLabel27.show(false);
            timer.start();
            cont3++;
        }


    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        if (!RightdoorClosed) {
            if (cont4 % 2 != 0) {
                jLabel14.show(false);
                jLabel21.show(true);
                jLabel2.setIcon(jLabel20.getIcon());
                jLabel2.show(true);
                cont4++;

                LeftLighton = true;
            } else {
                jLabel14.show(true);
                jLabel21.show(false);
                jLabel2.show(false);
                LeftLighton = false;
                cont4++;
            }
        } else {
            System.out.println("PlaySound");
        }

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (!LeftdoorClosed) {
            if (cont5 % 2 != 0) {
                RightLighton = true;
                jLabel16.show(false);
                jLabel24.show(true);
                jLabel6.setIcon(jLabel22.getIcon());
                jLabel6.show(true);
                cont5++;
            } else {
                RightLighton = false;
                jLabel16.show(true);
                jLabel24.show(false);
                jLabel6.show(false);
                cont5++;
            }

        } else {
            System.out.println("PlaySound2");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void Cam1AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cam1AMouseClicked
        System.out.println("SEXOOO");
    }//GEN-LAST:event_Cam1AMouseClicked

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void startClockSimulation() {
        if (clockWorker != null && !clockWorker.isDone()) {
            clockWorker.cancel(true);
        }

        clockWorker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() {
                try {
                    for (int minutos = 0; minutos <= 360; minutos++) {
                        int horas = minutos / 60;

                        String horaFormateada = String.format("%02d %s",
                                (horas % 12 == 0) ? 12 : horas % 12,
                                (horas < 12) ? "AM" : "PM");

                        publish(horaFormateada);

                        TimeUnit.MILLISECONDS.sleep(1000);

                        if (isCancelled()) {
                            break;
                        }
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
                return null;
            }

            @Override
            protected void process(java.util.List<String> chunks) {
                if (!chunks.isEmpty()) {
                    String ultimaHora = chunks.get(chunks.size() - 1);
                    jLabel18.setForeground(Color.WHITE);
                    jLabel18.setFont(jTextField2.getFont());
                    jLabel18.setText(ultimaHora);
                }
            }

            @Override
            protected void done() {
                JOptionPane.showMessageDialog(null, "¡Victoria! El reloj marca las 6:00 AM.");
                System.exit(0);
            }
        };
        clockWorker.execute();
    }
    private int cont = 1;
    private int cont3 = 1;
    private int cont2 = 1;
    private int cont4 = 1;
    private int cont5 = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cam1A;
    private javax.swing.JButton Cam1B;
    private javax.swing.JButton Cam1C;
    private javax.swing.JButton Cam2;
    private javax.swing.JButton Cam2A;
    private javax.swing.JButton Cam2B;
    private javax.swing.JButton Cam3;
    private javax.swing.JButton Cam4A;
    private javax.swing.JButton Cam4B;
    private javax.swing.JButton Cam5;
    private javax.swing.JButton Cam6;
    private javax.swing.JTextField Ds_Extra;
    private javax.swing.JTextField Ds_Extra2;
    private javax.swing.JTextField Ds_Extra3;
    private javax.swing.JDialog NewGame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
//
////      String nombre = jTextField6.getText().trim();
////
////        if (!jTextField6.getText().trim().isEmpty()) {
////            boolean usuarioExistente = false;
////
////            for (Usuario u : todo) {
////                if (u.getNombre().equalsIgnoreCase(nombre)) {
////                    usuarioExistente = true;
////                    break;
////                }
////            }
////
////            if (usuarioExistente) {
////                JOptionPane.showMessageDialog(this, "Este usuario ya existe. Debe ser un usuario único.");
////            } else {
////                Usuario u = new Usuario(nombre);
////                todo.add(u);
////
////                DefaultComboBoxModel modelo = (DefaultComboBoxModel) jComboBox1.getModel();
////                modelo.addElement(nombre);
////
////                jComboBox1.setModel(modelo);
////
////                jTextField6.setText("");
////
////                Admin ap
////                        = new Admin("./blady.txt");
////                ap.cargarArchivo();
////                ap.getListaPersonas().add(u);
////                try {
////                    ap.escribirArchivo();
////                } catch (IOException ex) {
////                    JOptionPane.showMessageDialog(this, "Algo fallo");
////                }
////
////            }
////        } else {
////            JOptionPane.showMessageDialog(this, "Debe ingresar una cadena");
////        }
//    ArrayList<Usuario> todo = new ArrayList();

}
